weight = int(input("Enter your weight: "))
print("you entered",weight)
height = float(input("\nEnter your height: "))
print("You entered", height)
age = int(input("\nEnter your age: "))
print("You entered", age)
bmr_Fem = 655.1 + (4.35 * weight) + (4.7 * height) - (4.7 * age)
bmr_Male = 66 + (6.2 * weight) + (12.7 * height) - (6.76 * age)
print("\nCalories needed to maintain your weight(Female):", bmr_Fem)
print("\nCalories needed to maintain your weight(Male):", bmr_Male)
